### ISSUE TITLE
look into coinbase intigration

### ISSUE THREAD

**Issue by lucaswadedavis** [defiant-light/defiant-light#19]

**Comment by toddskinner** [comment]
Possible to embed Coinbase payment button (one option)

![image](https://cloud.githubusercontent.com/assets/4375470/5863464/a761e7da-a22e-11e4-8239-9be3153d3a24.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5863470/af17fd7a-a22e-11e4-9095-102992eaf527.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5863474/b65d6d54-a22e-11e4-9d31-1bcad466adaf.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5863479/bcabf2d4-a22e-11e4-8078-bd8ae457e928.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5863483/c21346f0-a22e-11e4-8bc1-096404cde28a.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5863487/c84ce062-a22e-11e4-9947-6fe4161cd330.png)

**Comment by toddskinner** [comment]
Fuller description of "button" in Coinbase API

![image](https://cloud.githubusercontent.com/assets/4375470/5863722/7b811c60-a230-11e4-8f84-0d202f418715.png)

**Comment by toddskinner** [comment]
Options for triggering FauxPoe:
1.  Use a button per above to post order to API.  Then use Canary to check our wallet/account balance and if has changed/increased, trigger FauxPoe.

![image](https://cloud.githubusercontent.com/assets/4375470/5867201/b3f32ed6-a24d-11e4-9cbc-387b5e800fd9.png)
1.  Use a button per above to post order to API.  Provide callback URL and either:
2. check when redirected to that URL, that signals payment received so that triggers FauxPoe.  
3. set "order" callback so that it sends an order callback with a status of "completed".
4. set "address" callback to notify us when our bitcoin address receives a payment.
   (Looks like you can optionally set an address[callback_url] on an address to receive instant payment notifications whenever funds arrive to this address, but not quite sure how you do that yet).

![image](https://cloud.githubusercontent.com/assets/4375470/5867282/dfe97030-a24e-11e4-9b3b-68d3b130edfd.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5867288/eea04612-a24e-11e4-85c6-938a1ffbfb6a.png)

Order callback example:
![image](https://cloud.githubusercontent.com/assets/4375470/5867420/cc629a44-a250-11e4-8460-b744dc5cfa65.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5867433/05888216-a251-11e4-880e-c0a4456b100b.png)

Address callback example:
![image](https://cloud.githubusercontent.com/assets/4375470/5867430/faef014a-a250-11e4-88e7-dca98b7ae42a.png)

More info on callbacks:
![image](https://cloud.githubusercontent.com/assets/4375470/5867451/4b862264-a251-11e4-8d90-80087c280e5a.png)

**Comment by toddskinner** [comment]
Here are some examples of code, making simple API calls in Python:

![image](https://cloud.githubusercontent.com/assets/4375470/5867507/f016b7bc-a251-11e4-8885-77f7500d75ab.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5867512/07e3c3b2-a252-11e4-9750-16b5f5854250.png)

**Comment by toddskinner** [comment]
Am assuming if we use an orders callback, that callback will provide us with the transaction's associated email and/or bitcoin address that we will check against unfilled orders/email/BTCaddresses in our database. Otherwise, can query API for list of all transactions or orders per below. 

List Orders:
![image](https://cloud.githubusercontent.com/assets/4375470/5867626/8fe0ff40-a253-11e4-8e00-52ccd8e2e65d.png)

List Transactions:
![image](https://cloud.githubusercontent.com/assets/4375470/5867645/b271d9f8-a253-11e4-8e96-1be939b21fbc.png)
![image](https://cloud.githubusercontent.com/assets/4375470/5867651/c81048b2-a253-11e4-9cc2-d0207bc834e7.png)
